// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Moon.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Moon.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825221352_AddAdminAuth")]
    partial class AddAdminAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Moon.Api.Domain.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Complement")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Moon.Api.Domain.AdminRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AdminRefreshTokens");
                });

            modelBuilder.Entity("Moon.Api.Domain.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Moon.Api.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 1,
                            Name = "Alianças",
                            Slug = "aliancas"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 2,
                            Name = "Anéis",
                            Slug = "aneis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            DisplayOrder = 3,
                            Name = "Solitários",
                            Slug = "solitarios"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 4,
                            Name = "Colares",
                            Slug = "colares"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 5,
                            Name = "Brincos",
                            Slug = "brincos"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            DisplayOrder = 6,
                            Name = "Pulseiras",
                            Slug = "pulseiras"
                        });
                });

            modelBuilder.Entity("Moon.Api.Domain.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpiryMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ExpiryYear")
                        .HasColumnType("integer");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("LastFourDigits")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("Moon.Api.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LaunchedAt")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SalesCount")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 1,
                            Featured = true,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 1, 10),
                            Name = "Aliança Clássica Ouro 18k",
                            Price = 1890m,
                            SalesCount = 340,
                            Slug = "alianca-classica-ouro-18k"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 2,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 5, 2),
                            Name = "Aliança Trabalhada Ouro Rosé",
                            Price = 2150m,
                            SalesCount = 120,
                            Slug = "alianca-trabalhada-ouro-rose"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 3,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 11, 20),
                            Name = "Aliança Anatômica Prata",
                            Price = 690m,
                            SalesCount = 210,
                            Slug = "alianca-anatomica-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 4,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 3, 12),
                            Name = "Aliança Diamantada Ouro Branco",
                            Price = 2450m,
                            SalesCount = 88,
                            Slug = "alianca-diamantada-ouro-branco"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 5,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 7, 22),
                            Name = "Aliança Lisa Abaulada Prata",
                            Price = 520m,
                            SalesCount = 265,
                            Slug = "alianca-lisa-abaulada-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 6,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 7, 10),
                            Name = "Aliança Compromisso Ouro 18k",
                            Price = 2890m,
                            SalesCount = 42,
                            Slug = "alianca-compromisso-ouro-18k"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c1"),
                            DisplayOrder = 7,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 2, 1),
                            Name = "Aliança Textura Fosca Ouro Rosé",
                            Price = 2340m,
                            SalesCount = 130,
                            Slug = "alianca-textura-fosca-ouro-rose"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 8,
                            Featured = true,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 2, 14),
                            Name = "Anel Solitário Diamante",
                            Price = 4250m,
                            SalesCount = 95,
                            Slug = "anel-solitario-diamante"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 9,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 6, 1),
                            Name = "Anel Meia Aliança Zircônias",
                            Price = 990m,
                            SalesCount = 150,
                            Slug = "anel-meia-alianca-zirconias"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 10,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 9, 15),
                            Name = "Anel Vintage Ouro Branco",
                            Price = 1680m,
                            SalesCount = 80,
                            Slug = "anel-vintage-ouro-branco"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 11,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 4, 5),
                            Name = "Anel Cravejado Zircônias",
                            Price = 850m,
                            SalesCount = 175,
                            Slug = "anel-cravejado-zirconias"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 12,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 6, 20),
                            Name = "Anel Empilhável Ouro",
                            Price = 690m,
                            SalesCount = 210,
                            Slug = "anel-empilhavel-ouro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 13,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 10, 30),
                            Name = "Anel Signet Ouro Amarelo",
                            Price = 1290m,
                            SalesCount = 60,
                            Slug = "anel-signet-ouro-amarelo"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c2"),
                            DisplayOrder = 14,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 1, 15),
                            Name = "Anel Torcido Prata",
                            Price = 480m,
                            SalesCount = 190,
                            Slug = "anel-torcido-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            DisplayOrder = 15,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 3, 5),
                            Name = "Solitário Diamante 30pts",
                            Price = 6800m,
                            SalesCount = 40,
                            Slug = "solitario-diamante-30pts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            DisplayOrder = 16,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 12, 1),
                            Name = "Solitário Esmeralda",
                            Price = 5200m,
                            SalesCount = 25,
                            Slug = "solitario-esmeralda"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            DisplayOrder = 17,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 5, 8),
                            Name = "Solitário Safira Azul",
                            Price = 5900m,
                            SalesCount = 30,
                            Slug = "solitario-safira-azul"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            DisplayOrder = 18,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 9, 25),
                            Name = "Solitário Rubi",
                            Price = 6100m,
                            SalesCount = 22,
                            Slug = "solitario-rubi"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            DisplayOrder = 19,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 6, 30),
                            Name = "Solitário Diamante 50pts",
                            Price = 8900m,
                            SalesCount = 15,
                            Slug = "solitario-diamante-50pts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c3"),
                            DisplayOrder = 20,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 3, 20),
                            Name = "Solitário Ouro Rosé Diamante",
                            Price = 4700m,
                            SalesCount = 48,
                            Slug = "solitario-ouro-rose-diamante"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 21,
                            Featured = true,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 4, 18),
                            Name = "Colar Gota Prata",
                            Price = 590m,
                            SalesCount = 300,
                            Slug = "colar-gota-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 22,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 7, 1),
                            Name = "Colar Ponto de Luz Ouro",
                            Price = 1290m,
                            SalesCount = 60,
                            Slug = "colar-ponto-de-luz-ouro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 23,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 10, 10),
                            Name = "Colar Choker Prata",
                            Price = 450m,
                            SalesCount = 175,
                            Slug = "colar-choker-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 24,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 2, 28),
                            Name = "Colar Corrente Veneziana Ouro",
                            Price = 1650m,
                            SalesCount = 95,
                            Slug = "colar-corrente-veneziana-ouro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 25,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 5, 15),
                            Name = "Colar Coração Zircônia",
                            Price = 720m,
                            SalesCount = 220,
                            Slug = "colar-coracao-zirconia"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 26,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 12, 18),
                            Name = "Colar Corrente Cartier Prata",
                            Price = 890m,
                            SalesCount = 140,
                            Slug = "colar-corrente-cartier-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c4"),
                            DisplayOrder = 27,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 8, 5),
                            Name = "Colar Camafeu Vintage",
                            Price = 980m,
                            SalesCount = 55,
                            Slug = "colar-camafeu-vintage"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 28,
                            Featured = true,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 1, 25),
                            Name = "Brinco Argola Ouro",
                            Price = 780m,
                            SalesCount = 260,
                            Slug = "brinco-argola-ouro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 29,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 5, 20),
                            Name = "Brinco Ponto de Luz Diamante",
                            Price = 2100m,
                            SalesCount = 70,
                            Slug = "brinco-ponto-de-luz-diamante"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 30,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 8, 30),
                            Name = "Brinco Pérola Clássico",
                            Price = 620m,
                            SalesCount = 190,
                            Slug = "brinco-perola-classico"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 31,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 4, 22),
                            Name = "Brinco Cristal Gota",
                            Price = 560m,
                            SalesCount = 165,
                            Slug = "brinco-cristal-gota"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 32,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 6, 5),
                            Name = "Brinco Ear Cuff Prata",
                            Price = 390m,
                            SalesCount = 245,
                            Slug = "brinco-ear-cuff-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 33,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 11, 12),
                            Name = "Brinco Botão Ouro",
                            Price = 470m,
                            SalesCount = 200,
                            Slug = "brinco-botao-ouro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c5"),
                            DisplayOrder = 34,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 3, 30),
                            Name = "Brinco Comprido Cascata",
                            Price = 1120m,
                            SalesCount = 68,
                            Slug = "brinco-comprido-cascata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            DisplayOrder = 35,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 6, 15),
                            Name = "Pulseira Riviera Zircônias",
                            Price = 1450m,
                            SalesCount = 55,
                            Slug = "pulseira-riviera-zirconias"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            DisplayOrder = 36,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 11, 5),
                            Name = "Pulseira Berloques Prata",
                            Price = 540m,
                            SalesCount = 230,
                            Slug = "pulseira-berloques-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            DisplayOrder = 37,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 1, 5),
                            Name = "Pulseira Elos Ouro",
                            Price = 1580m,
                            SalesCount = 78,
                            Slug = "pulseira-elos-ouro"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            DisplayOrder = 38,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 5, 25),
                            Name = "Pulseira Tênis Zircônias",
                            Price = 2200m,
                            SalesCount = 50,
                            Slug = "pulseira-tenis-zirconias"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            DisplayOrder = 39,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2025, 9, 8),
                            Name = "Pulseira Corrente Cadeado Prata",
                            Price = 610m,
                            SalesCount = 185,
                            Slug = "pulseira-corrente-cadeado-prata"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CategoryId = new Guid("00000000-0000-0000-0000-0000000000c6"),
                            DisplayOrder = 40,
                            Featured = false,
                            IsActive = true,
                            LaunchedAt = new DateOnly(2026, 7, 5),
                            Name = "Pulseira Charm Coração",
                            Price = 490m,
                            SalesCount = 160,
                            Slug = "pulseira-charm-coracao"
                        });
                });

            modelBuilder.Entity("Moon.Api.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Moon.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Moon.Api.Domain.Address", b =>
                {
                    b.HasOne("Moon.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Moon.Api.Domain.AdminRefreshToken", b =>
                {
                    b.HasOne("Moon.Api.Domain.AdminUser", null)
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Moon.Api.Domain.PaymentMethod", b =>
                {
                    b.HasOne("Moon.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Moon.Api.Domain.Product", b =>
                {
                    b.HasOne("Moon.Api.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Moon.Api.Domain.RefreshToken", b =>
                {
                    b.HasOne("Moon.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
